version ="Two"
edition = "2018"
unstable_features = true

max_width = 120
newline_style = "Unix"

reorder_imports = true
imports_granularity="Crate"
group_imports="StdExternalCrate"

wrap_comments=true
normalize_comments =true

reorder_impl_items = true
condensewildcard_suffixes=true
enum_discrim_align_threshold=20
use_field_init_shorthand = true

format_strings = true
format_macro_matchers= true
format_codein_doc_comments=true
